apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-app
  namespace: demo-app
spec:
  dnsNames:
    - demo-app.american-broomstick.com
  secretName: demo-app-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
