apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./listener-set.yaml
  - ./route.yaml
  - ./https-redirect.yaml
  - ./certificate.yaml
